name: tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Prepare project for development
      run: |
        python -m pip install pytest


    - name: Run tests
      run: |
        pytest calculator.py
